###############################################
# Login
###############################################
# @name loginRequest
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}
###

@authToken = {{loginRequest.response.body.$.token}}



###############################################
# Create a new script
###############################################
POST {{baseUrl}}/api/v1/scripts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "My First Teleprompter Script",
  "description": "This is a detailed description for my first teleprompter script."
}

###

###############################################
# Get all scripts
###############################################
GET {{baseUrl}}/api/v1/scripts
Authorization: Bearer {{authToken}}

###

###############################################
# Get a single script
###############################################
GET {{baseUrl}}/api/v1/scripts/<SCRIPT_ID>
Authorization: Bearer {{authToken}}

###

###############################################
# Update a script
###############################################
PUT {{baseUrl}}/api/v1/scripts/<SCRIPT_ID>
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Updated Script Title",
  "description": "Updated description for the script."
}

###

###############################################
# Delete a script
###############################################
DELETE {{baseUrl}}/api/v1/scripts/<SCRIPT_ID>
Authorization: Bearer {{authToken}}
