@local = http://localhost:3000
@prod  = https://teleprompta.vercel.app/

@jwt   = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJjbWZ3YmNvdXgwMDAwMG14dzJzb3ZhcW0xIiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzU4NjIwOTM3fQ.w9nJ2Jqp-1DDLpFw52qGXYpppz5C_mznSgOszKbgIEk


###############################################
# Create a new script
###############################################
POST {{local}}/api/v1/scripts
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "My First Teleprompter Script",
  "description": "This is a detailed description for my first teleprompter script."
}

###

###############################################
# Get all scripts
###############################################
GET {{local}}/api/v1/scripts
Authorization: Bearer {{jwt}}

###

###############################################
# Get a single script
###############################################
GET {{local}}/api/v1/scripts/<SCRIPT_ID>
Authorization: Bearer {{jwt}}

###

###############################################
# Update a script
###############################################
PUT {{local}}/api/v1/scripts/<SCRIPT_ID>
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "Updated Script Title",
  "description": "Updated description for the script."
}

###

###############################################
# Delete a script
###############################################
DELETE {{local}}/api/v1/scripts/<SCRIPT_ID>
Authorization: Bearer {{jwt}}
